[Tue, 16 Jun 20 20:57:49 +0200][ERROR] {"message":"Response was already sent","trace":"#0 C:\\xampp\\htdocs\\mokubmsapi\\app\\plugins\\SecurityPlugin.php(160): Phalcon\\Http\\Response->send()\n#1 [internal function]: BMS\\Plugins\\SecurityPlugin->beforeException(Object(Phalcon\\Events\\Event), Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#2 [internal function]: Phalcon\\Events\\Manager->fireQueue(Array, Object(Phalcon\\Events\\Event))\n#3 [internal function]: Phalcon\\Events\\Manager->fire('dispatch:before...', Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#4 [internal function]: Phalcon\\Mvc\\Dispatcher->_handleException(Object(Phalcon\\Http\\Response\\Exception))\n#5 [internal function]: Phalcon\\Dispatcher->dispatch()\n#6 C:\\xampp\\htdocs\\mokubmsapi\\public\\index.php(48): Phalcon\\Mvc\\Application->handle('\/')\n#7 {main}"}
